import { useState, useEffect } from 'react';
import Navbar from './components/Navbar';
import MetricsDashboard from './components/MetricsDashboard';
import FailureForm from './components/FailureForm';
import AnalysisResultCard from './components/AnalysisResultCard';
import TransactionTable from './components/TransactionTable';
import 'bootstrap/dist/css/bootstrap.min.css';

const API_BASE = import.meta.env.VITE_API_URL || 'http://localhost:5000/api';

export default function App() {
  const [stats, setStats] = useState({
      totalTransactions: 0,
          successfulPayments: 0,
              failedPayments: 0,
                  successRate: 0,
                    });
                      const [transactions, setTransactions] = useState([]);
                        const [currentAnalysis, setCurrentAnalysis] = useState(null);
                          const [analyzedTxId, setAnalyzedTxId] = useState('');
                            const [loading, setLoading] = useState(false);
                              const [errorBanner, setErrorBanner] = useState('');

                                const loadData = async () => {
                                    try {
                                          const [statsRes, txRes] = await Promise.all([
                                                  fetch(`${API_BASE}/stats`),
                                                          fetch(`${API_BASE}/transactions`),
                                                                ]);

                                                                      const statsData = await statsRes.json();
                                                                            const txData = await txRes.json();

                                                                                  if (statsData.success) setStats(statsData.stats);
                                                                                        if (txData.success) setTransactions(txData.data);
                                                                                            } catch (err) {
                                                                                                  console.error('Failed to load initial data:', err);
                                                                                                      }
                                                                                                        };

                                                                                                          useEffect(() => {
                                                                                                              loadData();
                                                                                                                }, []);

                                                                                                                  const handleAnalyze = async (formData) => {
                                                                                                                      setLoading(true);
                                                                                                                          setErrorBanner('');
                                                                                                                              try {
                                                                                                                                    const res = await fetch(`${API_BASE}/analyze-payment`, {
                                                                                                                                            method: 'POST',
                                                                                                                                                    headers: { 'Content-Type': 'application/json' },
                                                                                                                                                            body: JSON.stringify(formData),
                                                                                                                                                                  });

                                                                                                                                                                        const json = await res.json();
                                                                                                                                                                              if (!json.success) {
                                                                                                                                                                                      throw new Error(json.message || 'Analysis failed');
                                                                                                                                                                                            }

                                                                                                                                                                                                  setCurrentAnalysis(json.analysis);
                                                                                                                                                                                                        setAnalyzedTxId(formData.transactionId);
                                                                                                                                                                                                              await loadData();
                                                                                                                                                                                                                  } catch (err) {
                                                                                                                                                                                                                        setErrorBanner(err.message);
                                                                                                                                                                                                                            } finally {
                                                                                                                                                                                                                                  setLoading(false);
                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                        };

                                                                                                                                                                                                                                          return (
                                                                                                                                                                                                                                              <div className="bg-light min-vh-100 pb-5">
                                                                                                                                                                                                                                                    <Navbar />
                                                                                                                                                                                                                                                          <div className="container">
                                                                                                                                                                                                                                                                  {errorBanner && (
                                                                                                                                                                                                                                                                            <div className="alert alert-danger alert-dismissible fade show" role="alert">
                                                                                                                                                                                                                                                                                        {errorBanner}
                                                                                                                                                                                                                                                                                                    <button
                                                                                                                                                                                                                                                                                                                  type="button"
                                                                                                                                                                                                                                                                                                                                className="btn-close"
                                                                                                                                                                                                                                                                                                                                              onClick={() => setErrorBanner('')}
                                                                                                                                                                                                                                                                                                                                                          ></button>
                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                            )}

                                                                                                                                                                                                                                                                                                                                                                                    <MetricsDashboard stats={stats} />

                                                                                                                                                                                                                                                                                                                                                                                            <div className="row">
                                                                                                                                                                                                                                                                                                                                                                                                      <div className="col-lg-7">
                                                                                                                                                                                                                                                                                                                                                                                                                  <FailureForm onAnalyze={handleAnalyze} loading={loading} />
                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="col-lg-5">
                                                                                                                                                                                                                                                                                                                                                                                                                                                  {currentAnalysis ? (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                <AnalysisResultCard
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                analysis={currentAnalysis}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                transactionId={analyzedTxId}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="card shadow-sm border-0 p-4 text-center text-muted h-75 d-flex justify-content-center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p className="mb-0">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Select or enter transaction failure parameters to see an instant AI root cause analysis.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <TransactionTable transactions={transactions} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          